# lextab.py. This file automatically created by PLY (version 3.4). Don't edit!
_tabversion   = '3.4'
_lextokens    = {'DO': 1, 'RETURN': 1, 'LESS_THAN_OR_EQUAL': 1, 'NUMBER': 1, 'GREATER_THAN': 1, 'WHILE': 1, 'MULTIPLY': 1, 'LESS_THAN': 1, 'TRUE': 1, 'MINUS': 1, 'DIVIDE': 1, 'RPAREN': 1, 'NOT_EQUALS': 1, 'POW': 1, 'PLUS': 1, 'CATCH': 1, 'MULTI_LINE_COMMENT_END': 1, 'ASSIGN': 1, 'XOR': 1, 'STRING': 1, 'FOR': 1, 'IS': 1, 'EQUALS': 1, 'ELSE': 1, 'TRY': 1, 'LPAREN': 1, 'MULTI_LINE_COMMENT_START': 1, 'SINGLE_LINE_COMMENT': 1, 'ID': 1, 'IF': 1, 'AND': 1, 'FALSE': 1, 'GREATER_THAN_OR_EQUAL': 1, 'BREAK': 1, 'CONTINUE': 1, 'EACH': 1, 'NOT': 1, 'OR': 1, 'MOD': 1}
_lexreflags   = 0
_lexliterals  = ''
_lexstateinfo = {'INITIAL': 'inclusive'}
_lexstatere   = {'INITIAL': [('(?P<t_NUMBER>[0-9]*\\.?[0-9]+)|(?P<t_ID>[a-zA-Z_][a-zA-Z0-9_]*)|(?P<t_CONTINUE>continue)|(?P<t_OR>or|\\|\\|)|(?P<t_RETURN>return)|(?P<t_AND>and|&&)|(?P<t_CATCH>catch)|(?P<t_NOT>not|!)|(?P<t_FALSE>False)|(?P<t_BREAK>break)|(?P<t_WHILE>while)|(?P<t_STRING>".*")|(?P<t_ELSE>else)|(?P<t_EACH>each)|(?P<t_TRUE>True)|(?P<t_FOR>for)|(?P<t_TRY>try)|(?P<t_XOR>xor)|(?P<t_LESS_THAN_OR_EQUAL><=)|(?P<t_IF>if)|(?P<t_LPAREN>\\()|(?P<t_PLUS>\\+)|(?P<t_MULTI_LINE_COMMENT_START>/*)|(?P<t_MULTIPLY>\\*)|(?P<t_DO>do)|(?P<t_POW>\\^)|(?P<t_NOT_EQUALS>!=)|(?P<t_SINGLE_LINE_COMMENT>//)|(?P<t_IS>is)|(?P<t_MOD>\\%)|(?P<t_EQUALS>==)|(?P<t_RPAREN>\\))|(?P<t_MULTI_LINE_COMMENT_END>/*)|(?P<t_GREATER_THAN_OR_EQUAL><=)|(?P<t_LESS_THAN><)|(?P<t_DIVIDE>/)|(?P<t_MINUS>-)|(?P<t_ASSIGN>=)|(?P<t_GREATER_THAN>>)', [None, ('t_NUMBER', 'NUMBER'), (None, 'ID'), (None, 'CONTINUE'), (None, 'OR'), (None, 'RETURN'), (None, 'AND'), (None, 'CATCH'), (None, 'NOT'), (None, 'FALSE'), (None, 'BREAK'), (None, 'WHILE'), (None, 'STRING'), (None, 'ELSE'), (None, 'EACH'), (None, 'TRUE'), (None, 'FOR'), (None, 'TRY'), (None, 'XOR'), (None, 'LESS_THAN_OR_EQUAL'), (None, 'IF'), (None, 'LPAREN'), (None, 'PLUS'), (None, 'MULTI_LINE_COMMENT_START'), (None, 'MULTIPLY'), (None, 'DO'), (None, 'POW'), (None, 'NOT_EQUALS'), (None, 'SINGLE_LINE_COMMENT'), (None, 'IS'), (None, 'MOD'), (None, 'EQUALS'), (None, 'RPAREN'), (None, 'MULTI_LINE_COMMENT_END'), (None, 'GREATER_THAN_OR_EQUAL'), (None, 'LESS_THAN'), (None, 'DIVIDE'), (None, 'MINUS'), (None, 'ASSIGN'), (None, 'GREATER_THAN')])]}
_lexstateignore = {'INITIAL': ''}
_lexstateerrorf = {'INITIAL': None}
