
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = "\xb5\xc3c\xca\x89\xed\xf3\x04K'\x01\xe3\xd6j\nL"
    
_lr_action_items = {'TRUE':([0,],[3,]),'FALSE':([0,],[2,]),'$end':([1,2,3,4,],[0,-3,-2,-1,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'statement':([0,],[4,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> statement','start',1,'p_start','swim.py',175),
  ('statement -> TRUE','statement',1,'p_statement_true','swim.py',187),
  ('statement -> FALSE','statement',1,'p_statement_false','swim.py',191),
]
