
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xc0\xa2l~<\xb1\xebXW\xfb\xc3\x05\xd6<\xcd='
    
_lr_action_items = {'STRING':([3,],[4,]),'RPAREN':([4,],[5,]),'ID':([0,],[2,]),'LPAREN':([2,],[3,]),'$end':([1,5,],[0,-1,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'function':([0,],[1,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> function","S'",1,None,None,None),
  ('function -> ID LPAREN STRING RPAREN','function',4,'p_function','SWIM.py',48),
]
